name: Tests

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Test
      run: |
        npm i
        npm test

  osx:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Test
      run: |
        npm i
        npm test

  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Test
      run: |
        npm i
        npm test
